name: Build and Test

on:
  push:
    branches: [workflows]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:ci
      - name: Test e2e
        run: npm run e2e:ci
      - name: Build
        run: npm run build:ci
